CREATE TABLE `USERS`(`ID` INT AUTO_INCREMENT PRIMARY KEY, `NAME` VARCHAR(16) NOT NULL, `BALANCE` INT NOT NULL);
INSERT INTO `USERS`(`NAME`, `BALANCE`) VALUES ('User0', 0);
INSERT INTO `USERS`(`NAME`, `BALANCE`) VALUES ('User1', 50);
INSERT INTO `USERS`(`NAME`, `BALANCE`) VALUES ('User2', 100);
INSERT INTO `USERS`(`NAME`, `BALANCE`) VALUES ('User3', 500);
INSERT INTO `USERS`(`NAME`, `BALANCE`) VALUES ('User4', 1000);